#!/bin/bash

source .env

# require local llm execution
curl -s --head http://localhost:8000 > /dev/null || exit 1;

source .venv/bin/activate

if ! pip list | grep -q "llama-index"; then
    echo "llama-index is not installed"
    pip install -r requirements.txt
fi

python3 main.py